default_language_version:
    python: python3.9
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: mixed-line-ending

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 23.12.1
      hooks:
          - id: black

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: [--max-line-length=80]

    # - repo: https://github.com/PyCQA/pylint
    #   rev: v3.0.2
    #   hooks:
    #       - id: pylint

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            args: [--prose-wrap=always, --print-width=90, --tab-width=4]
