defaults:
    - base_train_config
    - _self_

dataset:
    path: datasets/train/iris_train.csv
    target_column: class

model:
    path: models/svc_iris.bin
    optimizer_parameters:
        iterations: 10
        depth: 10
        learning_rate: 0.01
        loss_function: MultiClassOneVsAll
    custom_metrics:
        - Accuracy
        - TotalF1
        - PRAUC

scaler:
    path: scalers/scaler.bin

ml_flow:
    scheme: http
    host: 127.0.0.1
    port: 5000
